### ISSUE TITLE
More informative runtime log

### ISSUE THREAD

**Issue by Zlopez** [flatpak/flatpak#1933]
Currently one is unable to tell which commit corresponds to current version of runtime.
For example output of `flatpak remote-info --log flathub org.gnome.Sdk//3.28`
```
Ref: runtime/org.gnome.Sdk/x86_64/3.28
ID: org.gnome.Sdk
Arch: x86_64
Branch: 3.28
Collection ID: org.flathub.Stable
Date: 2018-07-24 18:32:00 +0000
Subject: build of org.gnome.Sdk, Tue Jul 24 13:22:15 UTC 2018
Commit: 3c986218253988f28c3d53e100d94fd99ab33b797572f55982b1b0dad375b912
Parent: 051f23fb090728d508e3db85be1127527dc997fea5fe790b96700d7a9800dcf6
Download size: 771.6 MB
Installed size: 2.1 GB
History:
 Subject: build of org.gnome.Sdk, Mon Jul 16 16:38:26 UTC 2018
 Date: 2018-07-16 22:39:33 +0000
 Commit: 051f23fb090728d508e3db85be1127527dc997fea5fe790b96700d7a9800dcf6

 Subject: build of org.gnome.Sdk, Fri Jun  8 18:37:26 UTC 2018
 Date: 2018-06-08 22:38:59 +0000
 Commit: dd61d67dda60f8b025de9b7fcd213a81e762f191283752a0d798aea5b4150535

 Subject: build of org.gnome.Sdk, Fri Jun  8 18:37:26 UTC 2018
 Date: 2018-06-08 22:38:59 +0000
 Commit: ab66d6e3a44fd5b4401b25afb5208a43f23a6ed6ec6b57be7266dd441a1c38b2

 Subject: build of org.gnome.Sdk, Mon Jun  4 18:04:21 UTC 2018
 Date: 2018-06-04 23:16:42 +0000
 Commit: cea71fe86d6961b4fe58046170f8dc8f8d4d04141ddf211e7cc6db44a18a0c49

 Subject: build of org.gnome.Sdk, Fri May 25 12:58:28 UTC 2018
 Date: 2018-05-25 18:32:24 +0000
 Commit: aa620ef24fe0ef73d1f3fbbbf391e8f30dbdaca8c08df19e152d96aa25b0323d

 Subject: build of org.gnome.Sdk, Tue May 22 18:47:22 UTC 2018
 Date: 2018-05-23 02:40:10 +0000
 Commit: 0de544c981212de2d4a4acd3cecc187b72f81c69db7aa9627b9a89fd61a640b1
```

Commits in the --log output doesn't correspond to any commit in [gnome-sdk-images](https://gitlab.gnome.org/GNOME/gnome-sdk-images).

Could we have actual commit hash in the --log?
