### ISSUE TITLE
/usr/bin/perl: bad interpreter: no such file or directory

### ISSUE THREAD

**Issue by linuxhw** [flatpak/flatpak#2154]
## Linux distribution and version
Ubuntu 18.04
## Flatpak version
1.0.2
## Description of the problem
Trying to run flatpak for my program:

    flatpak run org.linux_hardware.hw-probe
    /app/usr/bin/hw-probe-flatpak: /app/usr/bin/hw-probe: /usr/bin/perl: bad interpreter: no such file or directory

Should I add `Perl` interpreter to my flatpak package?

## Steps to reproduce
* Build https://github.com/linuxhw/hw-probe/blob/master/flatpak/org.linux_hardware.hw-probe.yaml
* Run:

        flatpak run org.linux_hardware.hw-probe

**Comment by TingPing** [comment]
Perl isn't in the runtime, yes you would have to build it: https://github.com/flathub/io.github.Hexchat.Plugin.Perl/blob/master/io.github.Hexchat.Plugin.Perl.json#L15-L47

**Comment by linuxhw** [comment]
Thank you!

**Comment by fastrizwaan** [comment]
Here's perl flatpak build fix, taken from https://github.com/Gnucash/gnucash-on-flatpak/blob/master/modules/perl.json
```
  - name: perl
    no-autogen: true
    config-opts:
    - "-des"
    - "-Duseshrplib"
    build-options:
      cflags: "-fPIC"
      ldflags: "-fpic"
    sources:
    - type: archive
      url: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
      sha256: efeb1ce1f10824190ad1cadbcccf6fdb8a5d37007d0100d2d9ae5f2b5900c0b4
    - type: script
      dest-filename: configure
      commands:
      - exec ./configure.gnu $@
    post-install:
    - chmod -R u+w /app/lib/perl5
```
