### ISSUE TITLE
Cannot choose a folder in Flatpak build

### ISSUE THREAD

**Issue by alexgleason** [flatpak/flatpak#2479]
## Linux distribution and version
Tested on elementary OS Loki 0.4 and Ubuntu 18.10

## Flatpak version
Flatpak 1.0.6

## Description of the problem
I've used Flatpak to build Solarus Game Engine, a Qt-based desktop program that helps people make games.

It must load these games as **folders**. This is what "File > Add quest..." is supposed to look like:

![screenshot from 2018-12-23 18 24 30](https://user-images.githubusercontent.com/3639540/50404718-0f430b00-0779-11e9-935e-446929eb783d.png)

I can click a **folder** and select "choose" and it chooses that whole folder.

However, the Flatpak build does not use the Qt file browser dialog. It uses the native system one. Here's the resulting Flatpak on elementary OS 0.4 Loki:

![screenshot from 2018-12-23 16 53 08](https://user-images.githubusercontent.com/3639540/50404737-6cd75780-0779-11e9-925f-9fed59465be2.png)

I cannot select a folder. The only option is "Open" which causes the file browser to navigate *into* the folder.

To be sure this wasn't an issue with elementary OS, I also tested on Ubuntu 18.10 with nearly the same result:

![hyctq3d](https://user-images.githubusercontent.com/3639540/50404747-90020700-0779-11e9-8e8a-f165da22b9ca.png)

Any ideas?

* Flatpak manifest file: https://gitlab.com/solarus-games/solarus/blob/dev/org.solarus_games.Solarus.json
* Related issue in the Solarus repo: https://gitlab.com/solarus-games/solarus/issues/1321

## Steps to reproduce

1. Clone Solarus and enter it:
```
git clone https://gitlab.com/solarus-games/solarus.git
cd solarus
```
2. Install KDE runtime and SDK 5.11:
```
flatpak install flathub org.kde.Platform//5.11 org.kde.Sdk//5.11
```
3. Build the Flatpak:
```
flatpak-builder build-dir org.solarus_games.Solarus.json
```
4. Run the launcher program:
```
flatpak-builder --run build-dir org.solarus_games.Solarus.json solarus-launcher
```
5. The Solarus Launcher GUI will start. Choose "File > Add quest..." and attempt to select a **folder**, but you can't.

Thank you, and happy holidays!

**Comment by TingPing** [comment]
This is a Qt bug, it shouldn't be using the portal to open folders.

**Comment by alexgleason** [comment]
I just saw this: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser

It doesn't look like selecting folders is actually supported by the xdg-desktop-portal spec at all? There's no mention of them.

**Comment by alexgleason** [comment]
Wait, so are you saying qt could use its own file chooser dialog from within the flatpak? I thought that wasn't possible due to the nature of the sandbox.

**Comment by matthiasclasen** [comment]
If you want to select a folder inside the sandbox, using a local file chooser works. There is no way to select a host-side folder at runtime.

**Comment by kirbyfan64** [comment]
Could this be a bug in the runtime itself?

**Comment by alexgleason** [comment]
For what it's worth, I tried creating a Snap and it did the same thing. Screenshot of my Snap build:

![screenshot from 2018-12-24 20 38 23](https://user-images.githubusercontent.com/3639540/50410613-12b1b300-07c8-11e9-81f7-bd90e0d25b12.png)

snapcraft.yml:
```
name: solarus
version: "1.6"
summary: A free and open-source Action-RPG game engine
description: |
  Solarus is a free and open-source Action-RPG game engine, licensed under GPL,
  and written in C++. It runs quests in Lua, and can work on a great number
  of platforms. Solarus also features a game editor called Solarus Quest Editor,
  written in C++ with Qt to help you create your game.

confinement: devmode

apps:
  solarus:
    command: desktop-launch solarus-launcher

parts:
  solarus:
    plugin: cmake
    source-type: git
    source: https://gitlab.com/solarus-games/solarus.git
    source-commit: 633bad6be5fbe2f77c3d63db497f7d7e2b1128f6
    build-packages:
      - g++
      - make
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libluajit-5.1-dev
      - libphysfs-dev
      - libopenal-dev
      - libmodplug-dev
      - libvorbis-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libglm-dev
    after: [desktop-qt5]
```
