### ISSUE TITLE
[QUESTION] Compiling libGLU as i386 in x64 machine

### ISSUE THREAD

**Issue by mantielero** [flatpak/flatpak#2586]
## Linux distribution and version
```
$ uname -a
Linux mountain 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux
```
## Flatpak version
```
$ flatpak --version
Flatpak 1.1.2
```
## Description of the problem
I am trying to pack EnemyTerritory. It is the x32 version of [etlegacy](https://www.etlegacy.com/). It depends on [GLU](ftp://ftp.freedesktop.org/pub/mesa/glu/) (from Mesa).

I am not managing to compile GLU as i386. 

## Steps to reproduce
I am using the following options:
```
$ flatpak run --devel --command=bash org.freedesktop.Etlegacy
$ cd /tmp/glu-9.0.0
$ CFLAGS=-m32 CXXFLAGS=-m32 ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/glu-9.0.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

When I do the same directly in the host, it compiles properly.

I have attached `config.log` for the [host](https://github.com/flatpak/flatpak/files/2753592/config.log.host.txt) and the [flatpak](https://github.com/flatpak/flatpak/files/2753594/config.log.flatpak.txt):

Probably I am missing something really obvious, given that I am not a developer.

I am using `flatpak-builder`. The most relevant bits are:
```yaml
app-id: org.freedesktop.Etlegacy

runtime: org.freedesktop.Platform
runtime-version: '18.08'
sdk: org.freedesktop.Sdk
separate-locales: false
command: /app/bin/etl


add-extensions:
  org.freedesktop.Platform.Compat.i386:
    directory: lib/i386-linux-gnu
    version: '18.08'

# For some reason is not working for me
#  org.freedesktop.Platform.Compat.i386.Debug:
#    directory: lib/debug/lib/i386-linux-gnu
#    version: '18.08'
#    no-autodownload: true


  org.freedesktop.Platform.GL32:
    directory: lib/i386-linux-gnu/GL
    version: '1.4'
    versions: 18.08;1.4
    subdirectories: true
    no-autodownload: true
    autodelete: false
    add-ld-path: lib
    merge-dirs: vulkan/icd.d;glvnd/egl_vendor.d
    download-if: active-gl-driver
    enable-if: active-gl-driver


modules:
   # Providing mounting points
   - name: setup_compat32
     buildsystem: simple
     build-commands:
      - mkdir -p /app/lib/i386-linux-gnu
      - mkdir -p /app/lib/debug/lib/i386-linux-gnu
      - mkdir -p /app/lib/i386-linux-gnu/GL

   - glu.yaml
```
