### ISSUE TITLE
Where modules sources are installed?

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak#3049]
- Linux distribution and version Manjaro Linux 18.0.4
- Flatpak version 1.4.2

## Description of the problem

This is more a help demand for building a flatpak than an issue report. I didn't find the good place for this, like a forum dedicated to building flatpaks.

I would like to create a Flatpak for [CQ-editor](https://github.com/CadQuery/CQ-editor), which provide [releases](https://github.com/CadQuery/CQ-editor/releases/tag/0.1RC1) of the software as an archive, with all necessary sources inside (.so & co), among with an executable. So typically, we just have to extract the archive, cd into the directory and run `CQ-editor`.

In the manifest, I added this archive in a module source, and now I would like to add a script that cd into them, and run the executable. Here is my manifest for now:

```yml
app-id: org.cadquery.cadquery-editor
runtime: org.kde.Platform
runtime-version: '5.12'
sdk: org.kde.Sdk
command: cadquery-editor
finish-args:
  - --socket=fallback-x11
  - --filesystem=home:rw
modules:
  - name: cadquery-editor
    buildsystem: simple
    build-commands:
      - install -D cadquery-editor.sh /app/bin/cadquery-editor
    sources:
      - type: archive
        url: https://github.com/CadQuery/CQ-editor/releases/download/0.1RC1/CQ-editor-0.1RC1-linux64.tar.bz2
        sha256: 6e93272680db4ffc27795a71e0490d0809c63c151f25c49bd30322ed9a2fb636
      - type: file
        path: cadquery-editor.sh
```

where `cadquery-editor.sh` is a script containing:

```bash
#!/bin/bash
cd /run/build
./CQ-editor
```

Here I know that `/run/build` is not the right path, because it contains the directories generated by flatpak-builder (`cadquery-editor-1`, `cadquery-editor-2`, etc.).

Which path should I use instead?
