### ISSUE TITLE
GL extensions not being installed as dependency

### ISSUE THREAD

**Issue by A6GibKm** [flatpak/flatpak#3072]
## Linux distribution and version
Fedora 30 and Fedora Silverblue 30
## Flatpak version
1.4.2
## Description of the problem
The packages `org.freedesktop.Platform.GL.default org.freedesktop.Platform.GL32.default` are not being installed as dependencies of `net.lutris.Lutris//beta`(flathub-beta repository),  even though the later is listed as a dependency of lutris:
```yaml
    org.freedesktop.Platform.GL32:
    directory: lib/i386-linux-gnu/GL
    version: "1.4"
    versions: "19.08beta;1.4"
    subdirectories: true
    no-autodownload: true
    autodelete: false
    add-ld-path: lib
    merge-dirs: vulkan/icd.d;glvnd/egl_vendor.d;OpenCL/vendors
    download-if: active-gl-driver
    enable-if: active-gl-driver
```
Without the 19.08beta version of these extensions Vulkan can't be initialized.

This is related to https://github.com/flathub/net.lutris.Lutris/issues/34
## Steps to reproduce
Add flathub-beta:
`flatpak remote-add --user flathub-beta https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo`
and then run:
`flatpak install flathub-beta net.lutris.Lutris//beta`

See: https://valentindavid.com/posts/2019-07-04-testing-mesa-aco-with-flatpak/
