### ISSUE TITLE
how to update to an older version?

### ISSUE THREAD

**Issue by OnTheLink** [flatpak/flatpak#3105]
Hello,

I tried to update to an older version using the --commit option but it gives the output:
update is older than current version

How do i force the update to continue even though it's an older version?

**Comment by aiamuzz** [comment]
@OnTheLink ...

run this command for the app you want to switch to an older version of ... in my case below, i've chosen qBittorrent

`flatpak remote-info --log flathub org.qbittorrent.qBittorrent`

Output : 
```
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1

qBittorrent - An open-source Bittorrent client

        ID: org.qbittorrent.qBittorrent
       Ref: app/org.qbittorrent.qBittorrent/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 4.1.7
   License: GPL-2.0 and OpenSSL
Collection: org.flathub.Stable
  Download: 8.1 MB
 Installed: 13.9 MB
   Runtime: org.kde.Platform/x86_64/5.12

       Sdk: org.kde.Sdk/x86_64/5.12
    Commit: 02d105ef51b5e9e1bd354125223e3da1704218588cdd32f568dd1116bf9f26bd
    Parent: 30315fcd1d34daf70a7247dad186a0f7c269a7e28e022bec7b5d1856638ce5f2
   Subject: qbittorrent-4.1.7 (e564a1d0)
      Date: 2019-08-05 20:37:04 +0000
   History: 

    Commit: 30315fcd1d34daf70a7247dad186a0f7c269a7e28e022bec7b5d1856638ce5f2
   Subject: update: qbittorrent 4.1.6, libtorrent 1.1.13 (cd63b3ba)
      Date: 2019-05-06 19:27:04 +0000

    Commit: 7fa6c51a76c69d7d7eac3d0d899777bbe7c7969209e2fd30ebbaa1e66f16e1f6
   Subject: Update dependencies (b1e83383)
      Date: 2019-01-20 17:05:33 +0000

    Commit: 6eb55eca743deb72299ea32447ba1167c060ddfbc48dae389eb8c6ceea0ca39b
   Subject: update: qbittorrent 4.1.5 (dd81e4a9)
      Date: 2018-12-25 01:13:15 +0000

    Commit: 771524b63d256fec82cd7ce67a59db774841b7f4222f83bb4e35e498983c13bd
   Subject: update: qbittorrent 4.1.4, libtorrent 1.1.11 (40127572)
      Date: 2018-11-19 19:47:19 +0000

    Commit: 33607aef2d993f00607449000d2d7553aa14c690249a8c369a66e7bd9e313073
   Subject: add yaml (dd07a994)
      Date: 2018-10-09 22:59:22 +0000
```

then you can choose the particular version and use the corresponding commit and run this command ...

`flatpak update --commit=30315fcd1d34daf70a7247dad186a0f7c269a7e28e022bec7b5d1856638ce5f2 org.qbittorrent.qBittorrent`
