### ISSUE TITLE
flatpak-builder: CMake file download doesn't work when running from flatpak-builder

### ISSUE THREAD

**Issue by froqstar** [flatpak/flatpak#3329]
## Linux distribution and version
Fedora 31

## Flatpak version
1.4.3

## Description of the problem
I am trying to build a flatpak for [opentx-companion](https://github.com/opentx/opentx/wiki/OpenTX-2.2-Linux-Build-Instructions). 
The CMake configuration is downloading some googletest files if it doesn't find them in the downloaded sources. This works fine when manually invoking `cmake .` in the downloaded sources:
```
-- Found Threads: TRUE  
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_LIBRARY_PATH SDL_INCLUDE_DIR) 
-- SDL not found! Simulator audio, and joystick inputs, will not work.
-- Googletest will be downloaded
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
...
-- [download 100% complete]
TARGET simu/libsimulator: cpp compiler /usr/bin/c++ v9
-- Added optional gtests target
```

However, when cmake is run by flatpak-builder, the download is skipped (Note the missing progress reporting):
```
-- Found Threads: TRUE  
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_LIBRARY_PATH SDL_INCLUDE_DIR) 
-- SDL not found! Simulator audio, and joystick inputs, will not work.
-- Googletest will be downloaded
TARGET simu/libsimulator: cpp compiler /usr/bin/c++ v8.3.0
-- Added optional gtests target
```
This causes the build to fail after the configuring stage.

The cmakefile line performing the download looks as follows:
```
file(DOWNLOAD "${GTEST_URL}" ${GTEST_ARCHIVE} SHOW_PROGRESS)
```

What do I need to specify/change to make this work?

## Steps to reproduce
My flatpak manifest:
```
id: org.opentx.Companion
runtime: org.kde.Platform
runtime-version: '5.12'
sdk: org.kde.Sdk
command: opentx-companion
modules:
    - name: companion
      buildsystem: cmake
      make-args: ['companion23']
      sources:
        - type: archive
          url: https://www.github.com/opentx/opentx/archive/release/2.3.3.tar.gz
          sha256: 3f5b39bdd643819166da632279fe35bfb256068bede29e17db09f4cb87738665
          
finish-args:
    - --share=network
    - --socket=x11
    - --socket=wayland
    - --filesystem=host
    
rename-desktop-file: companion.desktop
rename-icon: icon.png
```
