### ISSUE TITLE
Ghost updates with flatpak remote-ls --updates

### ISSUE THREAD

**Issue by fabricemarie** [flatpak/flatpak#3748]
## Linux distribution and version

Fedora SilverBlue 32

## Flatpak version

1.6.4 and reproduced with 1.8.1

## Description of the problem

Listing available updates give a list of packages that need updates **and** packages that have already been fully updated:

```
# flatpak remote-ls --updates
Name                   Application ID                   Version       Branch       Arch         Origin
Code - OSS             com.visualstudio.code-oss        1.47.1        stable       x86_64       flathub
Baobab                 org.gnome.Baobab                               stable       x86_64       fedora
GNOME Calculator       org.gnome.Calculator             3.36.0        stable       x86_64       fedora
Calendar               org.gnome.Calendar               3.36.1        stable       x86_64       fedora
GNOME Characters       org.gnome.Characters                           stable       x86_64       fedora
Contacts               org.gnome.Contacts               3.36.1        stable       x86_64       fedora
Evince                 org.gnome.Evince                 3.36.3        stable       x86_64       fedora
File Roller            org.gnome.FileRoller                           stable       x86_64       fedora
GNOME Logs             org.gnome.Logs                   3.34.0        stable       x86_64       fedora
GNOME Maps             org.gnome.Maps                   3.36.2        stable       x86_64       fedora
GNOME Screenshot       org.gnome.Screenshot             3.36.0        stable       x86_64       fedora
Weather                org.gnome.Weather                3.36.1        stable       x86_64       fedora
GNOME Clocks           org.gnome.clocks                 3.36.2        stable       x86_64       fedora
Eye of GNOME           org.gnome.eog                    3.36.2        stable       x86_64       fedora
GNOME Fonts            org.gnome.font-viewer            3.32.0        stable       x86_64       fedora
gedit                  org.gnome.gedit                  3.36.2        stable       x86_64       fedora
Platform               org.fedoraproject.Platform                     f32          x86_64       fedora
```

when the actual list of updates (gathered with `flatpak update`) is:

```
# flatpak update
Looking for updates…

New org.gnome.clocks permissions:
    fallback-x11



        ID                                  Branch          Op          Remote           Download
 1.     org.gnome.font-viewer               stable          u           fedora           < 253.6 kB
 2.     org.gnome.eog                       stable          u           fedora             < 1.4 MB
 3.     org.gnome.clocks                    stable          u           fedora             < 1.1 MB
 4.     org.gnome.Weather                   stable          u           fedora             < 5.8 MB
 5.     org.gnome.FileRoller                stable          u           fedora           < 335.2 kB
 6.     org.gnome.Evince                    stable          u           fedora            < 17.0 MB
 7.     org.gnome.Contacts                  stable          u           fedora             < 6.0 MB
 8.     org.gnome.Characters                stable          u           fedora           < 347.0 kB
 9.     org.gnome.Calendar                  stable          u           fedora             < 5.9 MB
10.     com.visualstudio.code-oss           stable          u           flathub           < 85.8 MB

Proceed with these changes to the system installation? [Y/n]: n
```

## Steps to reproduce
Compare the output of `flatpak remote-ls --updates` with `flatpak update`

## Question

What is the recommended way to list updates without installing them?

**Comment by mwleeds** [comment]
>What is the recommended way to list updates without installing them?

You can run `flatpak update` and answer `no` at the `Proceed...` prompt, as you did.

That said, it looks like `remote-ls --updates` is misbehaving.

**Comment by mwleeds** [comment]
Could you post the output of `flatpak info org.gnome.Baobab`?

**Comment by mwleeds** [comment]
Looking at the code the only obvious reason `remote-ls --updates` would differ from `update` is if the set of installed subpaths is incomplete, but that would mostly apply to locale extensions so doesn't seem like the explanation here.

**Comment by fabricemarie** [comment]
> Could you post the output of `flatpak info org.gnome.Baobab`?

```
# flatpak info org.gnome.Baobab
          ID: org.gnome.Baobab
         Ref: app/org.gnome.Baobab/x86_64/stable
        Arch: x86_64
      Branch: stable
      Origin: fedora
  Collection: 
Installation: system
   Installed: 328.2 kB
     Runtime: org.fedoraproject.Platform/x86_64/f32
         Sdk: org.fedoraproject.Sdk/x86_64/f32

      Commit: 5cceef41fb525e21210f3c08eec83f2794523ee59a5a03f852a5c628d059b0cf
     Subject: Export org.gnome.Baobab
        Date: 2020-03-31 17:52:51 +0000
      Alt-id: 2433aee27a9fdeaf7292ab2d072b22729fa0add69c0fff40d34c616b1db3f5e1
```

And for example with Map which was updated as well and still shows as a ghost:
```
# flatpak info org.gnome.Maps

GNOME Maps - Find places around the world

          ID: org.gnome.Maps
         Ref: app/org.gnome.Maps/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.36.2
     License: GPL-2.0-or-later
      Origin: fedora
  Collection: 
Installation: system
   Installed: 20.6 MB
     Runtime: org.fedoraproject.Platform/x86_64/f32
         Sdk: org.fedoraproject.Sdk/x86_64/f32

      Commit: 109bdae272aff90ded5db0b09faac7b05edcda92e7c6fc4490c348d40e47a5ad
     Subject: Export org.gnome.Maps
        Date: 2020-06-04 12:54:36 +0000
      Alt-id: 540ff90441f12390cdc1acab39ec00fe64e62870f9e38f1b377a0b77baf11e7d

```
