### ISSUE TITLE
Cannot autolaunch D-Bus without X11 $DISPLAY when installing flatpaks

### ISSUE THREAD

**Issue by dustymabe** [flatpak/flatpak#3847]
## Linux distribution and version

- Fedora 33

## Flatpak version

- flatpak-1.8.2-1.fc33.x86_64

## Description of the problem

Can't install flatpaks without graphical display

## Steps to reproduce

Set up a user repo pointing to the fedora remote.. Then try to install something in a non-graphical interface (i.e. SSH terminal):

```
$ /usr/bin/flatpak install --user -y fedora org.gnome.eog
Looking for matches…
error: Cannot autolaunch D-Bus without X11 $DISPLAY
```

This means things like the [flatpak ansible module](https://docs.ansible.com/ansible/latest/modules/flatpak_module.html) simply won't work:

```
# Install any flatpaks that we want to use                           
- block:                                                             
    - name: Install flatpaks                                         
      flatpak:                                                       
        name: "{{ item.flatpak }}"                                   
        state: present                                               
        method: user                                                 
        remote: fedora                                               
      become: yes                                                    
      become_user: dustymabe                                         
      with_items:                                                    
            - { name: eog,         flatpak: org.gnome.eog           }
            - { name: firefox,     flatpak: org.mozilla.Firefox     }
            - { name: gedit,       flatpak: org.gnome.gedit         }
            - { name: gimp,        flatpak: org.gimp.GIMP           }
            - { name: inkscape,    flatpak: org.inkscape.Inkscape   }
            - { name: thunderbird, flatpak: org.mozilla.Thunderbird }
```

```
TASK [common : Install flatpaks] ************************************************************************************************************************************************
failed: [media] (item={'name': 'eog', 'flatpak': 'org.gnome.eog'}) => {"ansible_loop_var": "item", "changed": false, "command": "/usr/bin/flatpak install --user -y fedora org.gnome.eog", "item": {"flatpak": "org.gnome.eog", "name": "eog"}, "msg": "Failed to execute flatpak command", "rc": 1, "stderr": "error: Cannot autolaunch D-Bus without X11 $DISPLAY\n", "stderr_lines": ["error: Cannot autolaunch D-Bus without X11 $DISPLAY"], "stdout": "Looking for matches…\nRequired runtime for org.gnome.eog/x86_64/stable (runtime/org.fedoraproject.Platform/x86_64/f32) found in remote fedora\n", "stdout_lines": ["Looking for matches…", "Required runtime for org.gnome.eog/x86_64/stable (runtime/org.fedoraproject.Platform/x86_64/f32) found in remote fedora"]}
```

**Comment by dustymabe** [comment]
cc @kalev @owtaylor - anybody in particular I could get to look at this issue?

**Comment by owtaylor** [comment]
https://pagure.io/fedora-lorax-templates/c/cc1155372046baa58f9d2cc27a9e5473bf05a3fb?branch=master has a workaround if you know that you aren't in a D-BUS session. Dealing with the case where DBUS_SESSION_BUS_ADDRESS. might be set or not is a little harder.

@alexlarsson would have an idea whether there's anything that could be reasonably done within Flatpak to make this work automatically. (In general, I don't think every application that has multiple components that talk to each other over D-Bus needs to grow code to launch a private bus. Is Flatpak somehow special?)

**Comment by fansari** [comment]
I have the same issue - even if I run the flatpak command under my user with su.

```
su - fansari -c 'flatpak update --assumeyes'
```
On the other hand: if I run the command

```
flatpak update --assumeyes
```
directly under my user - then it works.

Also I noticed that it does not always behave like this. In the past I could even run the flatpak update command directly as rooot.

**Comment by jistr** [comment]
I have observed the same, indeed it seems that Ansible flatpak module is broken by this on Fedora 33. I explicitly provided `DISPLAY` variable to the module, which then resulted in the following: `error: Failed to execute child process “dbus-launch” (No such file or directory)`. So i also explicitly provided also `DBUS_SESSION_BUS_ADDRESS` and i *made sure the address is valid by logging into the desktop environment with the user i ran Ansible as*.

This is what i put onto the Ansible task:

    environment:
      DISPLAY: :0
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus

It's not ideal to have to hardcode these variables, but since i only manage my user's flatpaks, it's good enough.

**Comment by ibotty** [comment]
Is there anything that can be done to fail gracefully, i.e only fail the remotes that need a service accessible over dbus.  Automation is way harder if one has to start a separate dbus session.

**Comment by dustymabe** [comment]
Thanks @jistr - the workaround worked well for me. Anyone know how we can fix this problem without working around it?

**Comment by dustymabe** [comment]
Note that using the become machinectl plugin seems to work for this because it creates a full user session. 

```yaml
      become: yes              
      become_user: dustymabe   
      become_method: machinectl
```

The only problem is that I was hitting is that the operation was timing out sometimes so I tried to adjust the timeout and hit an issue with the plugin not properly passing environment variables. I opened an issue for that at https://github.com/ansible-collections/community.general/issues/3809

**Comment by mrckndt** [comment]
Fwiw i'm seeing the same issue with Ansible and i'm using `ansible_facts["env"]["DBUS_SESSION_BUS_ADDRESS"]` and `ansible_facts["env"]["DISPLAY"]`. This way i don't need to set the env myself as mentioned by @jistr

**Comment by goshansp** [comment]
installing `dbus-x11` and using `sudo $(dbus-launch) flatpak update --noninteractive` worked for me on Fedora 36 Silverblue, for systems where my user's id was not 1000. apparently systems where my user is id 1000 `flatpak update --noninteractive` works without any tricks.

**Comment by 1player** [comment]
> installing `dbus-x11` and using `dbus-launch flatpak update --noninteractive` worked for me on Fedora 36 Silverblue.

Keep in mind that recent Fedora versions have adopted dbus-broker, so `/usr/bin/dbus-launch` doesn't exist any more but should instead be replaced with `/usr/bin/dbus-run-session`. No need to install anything.

**Comment by Summertime** [comment]
Currently this seems to be preventing running `flatpak repair` as root, which doesn't and shouldn't have an X11 session.

**Comment by Thulium-Drake** [comment]
For those running Ansible and having trouble managing flatpaks, you can also configure your play like this:

```
- name: 'Ensure flatpak wrapper'
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      # This file is managed by Ansible, YOUR CHANGES WILL BE LOST!
      # This script works around an issue that flatpak requires a D-BUS session to work
      /usr/bin/dbus-run-session /usr/bin/flatpak $@
    dest: '/usr/bin/flatpak-wrapper'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Ensure flatpaks from Fedora'
  community.general.flatpak:
    name:
      - 'com.github.tchx84.Flatseal'
      - 'org.mozilla.Thunderbird'
      - 'org.zealdocs.zeal'
    remote: 'fedora'
    method: 'system'
    executable: '/usr/bin/flatpak-wrapper'
```
