### ISSUE TITLE
OpenCL not working inside of the sandbox

### ISSUE THREAD

**Issue by thejavascriptman** [flatpak/flatpak#3900]
## Linux distribution and version
Arch Linux with kernel 5.4.70-1-lts

```
$ pacman -Q | grep -Ei 'nvidia|ocl-icd|clinfo'
clinfo 2.2.18.04.06-2
nvidia-lts 1:455.28-4
nvidia-settings 455.28-1
nvidia-utils 455.28-1
ocl-icd 2.2.12-4
opencl-nvidia 455.28-1

$ flatpak list
Name                                    Application ID                                          Version                      Branch            Origin                     Installation
clinfo                                  com.example.clinfo                                                                   stable            clinfo-origin              user
GPU-Viewer                              io.github.arunsivaramanneo.GPUViewer                    1.15                         master            gpuviewer-origin           user
Freedesktop Platform                    org.freedesktop.Platform                                18.08.39                     18.08             flathub                    system
Freedesktop Platform                    org.freedesktop.Platform                                20.08.0                      20.08             flathub                    system
default                                 org.freedesktop.Platform.GL.default                                                  20.08             flathub                    system
nvidia-455-28                           org.freedesktop.Platform.GL.nvidia-455-28                                            1.4               flathub                    system
html5-codecs                            org.freedesktop.Platform.html5-codecs                                                18.08             flathub                    system
openh264                                org.freedesktop.Platform.openh264                       2.1.0                        2.0               flathub                    system
Freedesktop SDK                         org.freedesktop.Sdk                                     18.08.39                     18.08             flathub                    system
Freedesktop SDK                         org.freedesktop.Sdk                                     20.08.0                      20.08             flathub                    system
i386                                    org.freedesktop.Sdk.Compat.i386                                                      20.08             flathub                    system
toolchain-i386                          org.freedesktop.Sdk.Extension.toolchain-i386                                         20.08             flathub                    system
Adwaita theme                           org.kde.KStyle.Adwaita                                                               5.12              flathub                    system
KDE Application Platform                org.kde.Platform                                                                     5.12              flathub                    system
KDE Software Development Kit            org.kde.Sdk                                                                          5.12              flathub                    system
```

## Flatpak version
1.8.1

## Description of the problem
When running `clinfo -l` inside of the sandbox nothing is printed (meaning no OpenCL devices were detected) however if I run it outside of the sandbox I get the name of my graphics card (which is the expected behavior)

```
# host
$ clinfo -l
Platform #0: NVIDIA CUDA
 `-- Device #0: GeForce RTX 2070

# sandbox (outputs nothing)
$ clinfo -l
```

## Steps to reproduce

I tried this package from Flathub https://flathub.org/apps/details/io.github.arunsivaramanneo.GPUViewer as well as a custom package, OpenCL is not working in any of those.

Minimal example:

```
app-id: com.example.clinfo
runtime: org.freedesktop.Platform
runtime-version: '20.08'
sdk: org.freedesktop.Sdk
command: helloworld
default-branch: stable
separate-locales: false

finish-args:
  - --share=ipc
  - --socket=x11
  - --device=dri
  - --device=all

add-extensions:
  org.freedesktop.Platform.GL:
    directory: lib/GL
    version: '1.4'
    versions: 20.08;1.4
    subdirectories: true
    no-autodownload: true
    autodelete: false
    add-ld-path: lib
    merge-dirs: vulkan/icd.d;glvnd/egl_vendor.d
    download-if: active-gl-driver
    enable-if: active-gl-driver

modules:
  - name: clinfo
    no-autogen: true
    no-make-install: true
    build-commands:
      - install -Dm755 -t /app/bin/ clinfo
    sources:
      - type: archive
        url: "https://github.com/Oblomov/clinfo/archive/2.2.18.04.06.tar.gz"
        sha256: f77021a57b3afcdebc73107e2254b95780026a9df9aa4f8db6aff11c03f0ec6c
    modules:
      - name: ocl-icd
        sources:
          - type: archive
            url: "https://github.com/OCL-dev/ocl-icd/archive/v2.2.13.tar.gz"
            sha256: f85d59f3e8327f15637b91e4ae8df0829e94daeff68c647b2927b8376b1f8d92
          - type: script
            dest-filename: autogen.sh
            commands:
              - autoreconf -fiv
      - name: opencl-headers
        buildsystem: simple
        build-commands:
          - cp -av opencl22/CL /app/include
        sources:
          - type: git
            url: "https://github.com/KhronosGroup/OpenCL-Headers.git"
            commit: e986688daf750633898dfd3994e14a9e618f2aa5

  - name: helloworld
    buildsystem: simple
    sources:
      - type: script
        dest-filename: helloworld.sh
        commands:
          - zenity --info --text="$(clinfo -l)"
    build-commands:
      - mkdir -p ${FLATPAK_DEST}/lib/GL
      - install -Dm755 helloworld.sh ${FLATPAK_DEST}/bin/helloworld
```
