### ISSUE TITLE
SSL error in flatpak apps

### ISSUE THREAD

**Issue by diegogangl** [flatpak/flatpak#4118]
## Linux distribution and version

Fedora 33

## Flatpak version

Flatpak 1.10.1

## Description of the problem

SSL fails somehow when trying to connect to a server from a flatpak app.
I've noticed this in Epiphany (website not trusted error), Tootle (SSL Handshake failed) and Steam (same error). The solution in #2921 (Network Manager) didn't work.

p11-kit is up to date:

```
▶ p11-kit list-modules -v    
p11-kit-trust: p11-kit-trust.so
    library-description: PKCS#11 Kit Trust Module
    library-manufacturer: PKCS#11 Kit
    library-version: 0.23
    token: System Trust
        manufacturer: PKCS#11 Kit
        model: p11-kit-trust
        serial-number: 1
        hardware-version: 0.23
        flags:
               write-protected
               token-initialized
    token: Default Trust
        manufacturer: PKCS#11 Kit
        model: p11-kit-trust
        serial-number: 1
        hardware-version: 0.23
        flags:
               write-protected
               token-initialized
opensc: opensc-pkcs11.so
    library-description: OpenSC smartcard framework
    library-manufacturer: OpenSC Project
    library-version: 0.21
```

## Steps to reproduce

Open either Epiphany, Tootle or Steam and try to connect
