### ISSUE TITLE
[Bug]: PySide6 linking error

### ISSUE THREAD

**Issue by v-ko** [flatpak/flatpak#5103]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Manjaro Linux

### Linux distribution version

5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

With this manifest:
```
app-id: org.bug.reproduce
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: reproduce

modules:
  - name: reproduce
    buildsystem: simple
    build-commands:
      - pip3 install --prefix=/app PySide6
      - echo 'python -c "from PySide6.QtNetwork import QNetworkReply"' > /app/bin/reproduce
      - chmod +x /app/bin/reproduce
build-options:
  build-args:
  - --share=network

finish-args:
  - --socket=x11
  - --socket=wayland
  - --share=network
  - --filesystem=host

```
Build: `flatpak-builder --repo=test_flatpak builds/flatpak ./org.bug.reproduce.yml --force-clean`
Add the repo (once): `flatpak --user remote-add --no-gpg-verify reproduce-repo test_flatpak/`
Install the app: `flatpak --user install reproduce-repo org.bug.reproduce`
And run it: `flatpak run org.bug.reproduce`

Output: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
```

### Expected Behavior

For the PySide6 installation to work.

### Actual Behavior

PySide6 fails to load. I would report the bug to Qt, but I suspect it's some platform/sdk problem with Flatpak that I can't solve.

### Additional Information

For the record - I know that it's a bad practice to enable networking for the build, no reproducibility, etc. , but I don't believe that's the issue here.
