### ISSUE TITLE
[Bug]: flatpak-builder: Unknown property cleanup-commands for type BuilderModule

### ISSUE THREAD

**Issue by stevenlafl** [flatpak/flatpak#5113]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.0

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

20220918.0.86346

### What architecture are you using?

x86_64

### How to reproduce

1. Add 'cleanup-commands' as specified in the docs under modules. Example:
```
modules:
  - name: pam
    buildsystem: autotools
    cleanup-commands:
      - mkdir /app/includes/security
      - mv /app/include/pam_appl.h /app/includes/security/pam_appl.h
    sources:
      - url: https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/pam/1.4.0-11ubuntu2/pam_1.4.0.orig.tar.xz
        sha256: cd6d928c51e64139be3bdb38692c68183a509b83d4f2c221024ccd4bcddfd034
        type: archive
```

### Expected Behavior

It should execute the cleanup commands as part of cleanup, so I can move files around to the proper locations.

### Actual Behavior

I receive the error:
```
Unknown property cleanup-commands for type BuilderModule
```
