### ISSUE TITLE
There is a difference between building SDK extensions and building in sdk

### ISSUE THREAD

**Issue by q962** [flatpak/flatpak#5137]
```yaml
id: org.freedesktop.Sdk.Extension.zsh                    
runtime: org.freedesktop.Sdk                             
runtime-version: '21.08'                                 
branch: '21.08'                                          
sdk: org.freedesktop.Sdk                                 
build-extension: true                                    
separate-locales: false                                  
appstream-compose: false                                 
extension-tag: org.freedesktop.Sdk.Extension             
modules:                                                 
  - name: zsh                                            
    sources:                                             
      - type: git                                        
        url: https://github.com/zsh-users/zsh.git        
          #tag: zsh-5.9                                  
        branch: 'master'                                 
    buildsystem: simple                                  
    build-commands:                                      
      - autoreconf -fi                                   
      - ./configure --prefix=$FLATPAK_DEST               
      - sed -i 's/install.man install.runhelp//' Makefile
      - make install                                     
```

run sdk extension
```shell
# demo @ demo-PC in ~/project/open_source_project/zsh[10:26:53] C:130
$ SH=/usr/lib/sdk/zsh/bin/zsh flatpak-toolbox

# demo @ GNOME 42 (Flatpak runtime) in ~/project/open_source_project/zsh [10:27:01] C:1
$


# demo @ GNOME 42 (Flatpak runtime) in ~/project/open_source_project/zsh [10:27:02] C:130

# demo @ demo-PC in ~/project/open_source_project/zsh [10:27:02] C:130
$
zsh: error on TTY read: 输入/输出错误
```

build in sdk
```shell
# demo @ demo-PC in ~/project/open_source_project/zsh [10:29:25]
$ SH=`pwd`/dist4/bin/zsh flatpak-toolbox

# demo @ GNOME 42 (Flatpak runtime) in ~/project/open_source_project/zsh [10:29:33] C:1
$

# demo @ GNOME 42 (Flatpak runtime) in ~/project/open_source_project/zsh [10:29:33] C:130
$

# demo @ GNOME 42 (Flatpak runtime) in ~/project/open_source_project/zsh [10:29:35] C:130
$

# demo @ GNOME 42 (Flatpak runtime) in ~/project/open_source_project/zsh [10:29:35] C:130
```

flatpak-toolbox
```shell
 env -i \
   XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
   TERM=screen-256color \
   LANG=zh_CN.UTF-8 \
   HOST="GNOME 42 (Flatpak runtime)" \
   /home/demo/.local/bin/flatpak run \
   --command="$SH" \
   --filesystem=host \
   ${SDK:-org.gnome.Sdk//42} "$@"
```

Why is there this difference?

Both use org.freedesktop.Sdk//21.08

flatpak 1.12.7
