### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RafaelPalomar** [flatpak/flatpak#5306]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.3

### What Linux distribution are you using?

Gentoo Linux

### Linux distribution version

Linux tp51 5.15.88-gentoo-dist

### What architecture are you using?

x86_64

### How to reproduce

Trying to build the following flatpak with `flatpak-builder --force-clean build-dir org.slicer.Slicer.yaml --verbose`:

```yaml
app-id: org.slicer.Slicer
runtime: org.kde.Platform
runtime-version: '5.15'
sdk: org.kde.Sdk
# KDE runtime environment does not provide the QtWebEngine component
# required for 3D Slicer
base: io.qt.qtwebengine.BaseApp
base-version: '5.15-22.08'
command: Slicer
finish-args:
  - |
      --device=dri
      --share=network
      --share=ipc
      --socket=x11
      --device=dri
      --filesystem=host
      --socket=wayland
modules:
  - name: Slicer
    buildsystem: simple
    build-commands:
      - ls
    sources:
      - type: git
        url: https://github.com/Slicer/Slicer.git
        tag: main
      - type: patch
        path: patches/01-ENH-Disable-https-check.patch
      - type: git
        url: https://github.com/commontk/bzip2
```
The `patches/01-ENH-Disable-https-check.patch` file is as follows:

```patch
diff --git a/SuperBuild.cmake b/SuperBuild.cmake
index 51eabb7d9d..9436412b6b 100644
--- a/SuperBuild.cmake
+++ b/SuperBuild.cmake
@@ -22,7 +22,7 @@
 #-----------------------------------------------------------------------------
 # CMake https support
 #-----------------------------------------------------------------------------
-include(SlicerCheckCMakeHTTPS)
+#include(SlicerCheckCMakeHTTPS)
 
 #-----------------------------------------------------------------------------
 # Git protocol option
```

### Expected Behavior

I would expect the process not to fail with the error `error: pathspec 'master' did not match any file(s) known to git`

### Actual Behavior

The flatpak build fails with the following output:

```txt
FB: Running: git config --get user.email
FB: Running: git config --get user.name
Emptying app dir 'build-dir'
FB: Running: flatpak info --arch=x86_64 --show-commit org.kde.Sdk 5.15
FB: Running: flatpak info --show-location --arch=x86_64 org.kde.Sdk 5.15
FB: Running: flatpak info --arch=x86_64 --show-commit org.kde.Platform 5.15
FB: Running: flatpak info --arch=x86_64 --show-commit io.qt.qtwebengine.BaseApp 5.15-22.08
Downloading sources
FB: Running: git --version
FB: Git version: 2.39.1.0
FB: Running: git cat-file -e main
FB: Running: git ls-remote origin
FB: Running: git config transfer.fsckObjects 1
Fetching git repo https://github.com/Slicer/Slicer.git, ref refs/heads/main
FB: Running: git fetch -p --no-recurse-submodules --depth=1 -f origin '+refs/heads/main:refs/heads/main'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
FB: Running: git rev-parse main
FB: Running: git rev-parse --verify --quiet 9506e42834364ad528f5e26c0150ca25e4c44999:.gitmodules
FB: Running: git ls-remote --symref https://github.com/commontk/bzip2 HEAD
FB: Failed to auto-detect default branch from git output
FB: Running: git --version
FB: Git version: 2.39.1.0
FB: Running: git cat-file -e master
FB: Running: git ls-remote origin
FB: Running: git config transfer.fsckObjects 1
Fetching git repo https://github.com/commontk/bzip2, ref refs/heads/master
FB: Running: git fetch -p --no-recurse-submodules --depth=1 -f origin '+refs/heads/master:refs/heads/master'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
FB: Running: git rev-parse master
FB: Running: git rev-parse --verify --quiet 391dddabd24aee4a06e10ab6636f26dd93c21308:.gitmodules
Starting build of org.slicer.Slicer
FB: Running: git rev-parse main
FB: Running: git rev-parse master
Cache miss, checking out last cache hit
FB: Mounting read-only fs: rofiles-fuse /home/rafael/src/Slicer-Flatpak/build-dir /home/rafael/src/Slicer-Flatpak/.flatpak-builder/rofiles/rofiles-aFy2ZS
========================================================================
Building module Slicer in /home/rafael/src/Slicer-Flatpak/.flatpak-builder/build/Slicer-2
========================================================================
FB: Running: cp -al /home/rafael/src/Slicer-Flatpak/.flatpak-builder/git/https_github.com_Slicer_Slicer.git /home/rafael/src/Slicer-Flatpak/.flatpak-builder/build/Slicer-2/.git
FB: Running: git config --bool core.bare false
FB: Running: git checkout main
Switched to branch 'main'
FB: Running: git rev-parse --verify --quiet main:.gitmodules
Applying patch 01-ENH-Disable-https-check.patch
FB: Running: patch -p1 -i /home/rafael/src/Slicer-Flatpak/patches/01-ENH-Disable-https-check.patch
patching file SuperBuild.cmake
FB: Running: cp -al /home/rafael/src/Slicer-Flatpak/.flatpak-builder/git/https_github.com_commontk_bzip2 /home/rafael/src/Slicer-Flatpak/.flatpak-builder/build/Slicer-2/.git
FB: Running: git config --bool core.bare false
FB: Running: git checkout master
error: pathspec 'master' did not match any file(s) known to git
Error: module Slicer: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /home/rafael/src/Slicer-Flatpak/.flatpak-builder/rofiles/rofiles-aFy2ZS
```
