### ISSUE TITLE
[Question]: Correct paths to include library from local file

### ISSUE THREAD

**Issue by robertosw** [flatpak/flatpak#5627]
I am not sure if this type of issue is wanted here, if not please let me know.

I am developing a tauri app inside a docker container running Debian 12. I know that this application runs in this docker container, so the correct libraries are installed. I exported the app as a .deb package, unpacked this and got the following `control` file:

```
Package: finanzbuch
Version: 0.1.7
Architecture: amd64
Installed-Size: 7022
Maintainer: Robert Oswald
Depends: libwebkit2gtk-4.0-37, libgtk-3-0
Description: ...
Priority: optional
```

This is the .deb unpacked
```
|-- deb-unpacked
|   |-- control
|   |-- debian-binary
|   |-- md5sums
|   `-- usr
|       |-- bin
|       |   `-- finanzbuch
|       `-- share
|           |-- applications
|           |   `-- finanzbuch.desktop
|           `-- icons
                ...
```

This implies that in order to create a flatpak, I would need to copy the binary and these two libraries. I tried doing this in my manifest file:
```
id: org.robertosw.finanzbuch
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: finanzbuch
modules:
  - name: libwebkit
    buildsystem: simple
    sources:
      - type: file
        path: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37.67.6
    build-commands:
      - "install -Dm644 libwebkit2gtk-4.0.so.37.67.6 /app/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37.67.6"
      - "ln -s libwebkit2gtk-4.0.so.37.67.6 /app/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37"
      - "ln -s libwebkit2gtk-4.0.so.37 /app/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so"
  
  - name: libgtk
    buildsystem: simple
    sources:
      - type: file
        path: /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2406.32
    build-commands:
      - "install -Dm644 libgtk-3.so.0.2406.32 /app/lib/x86_64-linux-gnu/libgtk-3.so.0.2406.32"
      - "ln -s libgtk-3.so.0.2406.32 /app/lib/x86_64-linux-gnu/libgtk-3.so.0"
      - "ln -s libgtk-3.so.0 /app/lib/x86_64-linux-gnu/libgtk-3.so"
  
  - name: binary
    buildsystem: simple
    build-commands:
      - install -Dm755 finanzbuch /app/bin/finanzbuch
    sources:
      - type: file
        path: ./deb-unpacked/usr/bin/finanzbuch
```

Building and Installing this works without problems. If I run this, I get this error:
`error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory`

I searched this up online, but couldn't find anything useful. I have a few ideas but I'd just like to get some help.
- Either these two libraries cant find their dependencies and I would have to import all them + the next level of dependencies ...
- Or the path inside the flatpak is wrong
