### ISSUE TITLE
[Feature request]: Bulk installation from a yaml file

### ISSUE THREAD

**Issue by yhojann-cl** [flatpak/flatpak#5809]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

For example, every time I am going to format my computer to update the distribution I need to run a bash script that installs everything automatically. It would be good if instead of executing a command for each application I could indicate the path of a file with the list of applications to install, something similar to the `package.json` file for `npm`, `Dockerfile` for docker or `requirements.txt` for `python` `pip`.

Like as:

```bash
flatpak install --file 'apps-pc-01yaml'
```

If, in addition to this, I could configure access to external disks for some apps such as Mozilla Firefox, Visual Studio, Krita, Steam and others in the same file, it would be great, like as:

```yaml
schema: flatpak:x.0
repository:
  url: https://flathub.org/repo/flathub.flatpakrepo
  apps:
    org.kde.krita
    org.xonotic.Xonotic
    com.valvesoftware.Steam:
      filesystem: /media/$USER
    org.videolan.VLC
      filesystem: /media/$USER
```

It could also be used for installations from vendors or distributions that require an installation with default applications from flathub, this would avoid ending and starting the terminal prompt in each application, the progress would be centralized in a single task reducing time and being friendlier with installations.
