### ISSUE TITLE
[Bug]: app breaks launching git when launched via flatpak run and works when exec-ed into flatpak and run from shell 

### ISSUE THREAD

**Issue by ndom91** [flatpak/flatpak#5998]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.6

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

24.04

### What architecture are you using?

x86_64

### How to reproduce

Attempting to build the flatpak manifest from [this PR](https://github.com/gitbutlerapp/gitbutler/pull/5473) works. However, I'm having trouble getting our application, GitButler, to be able communicate with ssh / git. Building the GitButler flatpak from the .deb does work, the application starts up. 

However, during operation we exec out to the git binary (from the host) to `fetch` and `pull`. This requires us to setup an askpass socket, this is done by a side-car binary of ours usually at `/tmp/gitbutler-askpass-[randomId]` to help with ssh authentication for git.

When trying to do one of those actions (fetch/pull), GitButler in the flatpak fails with `Could not find file or directory`. I'm not sure what file or dir its talking about, but I can access `git`, `ssh`, our `askpass` helper bin and they're all in `$PATH`. I cannot, however, find the askpass socket that's supposed to be created under `/tmp/gitbutler-askpass-..`.

All of this is to say, it seems like we're having trouble creating the socket in /tmp. I can't find it when exec-ed into the flatpak environment.

### Expected Behavior
 
GitButler is able to git feyxh

### Actual Behavior

 gitbutler forkexec git fetch throws an error about 'fike or dir not found'. 

The actual command we're executing which results in this error message is:

`
cd "/home/ndo/Documents/ndomino/react-timezone-select" && DISPLAY=":" GITBUTLER_ASKPASS_PIPE="/tmp/gitbutler-askpass-17236468319197446380" GITBUTLER_ASKPASS_SECRET="123abc" GIT_SSH_COMMAND="/app/bin/gitbutler-git-setsid ssh -o StrictHostKeyChecking=accept-new -o KbdInteractiveAuthentication=no" GIT_TERMINAL_PROMPT="0" LC_ALL="C" SSH_ASKPASS="/app/bin/gitbutler-git-askpass" "git" "-c" "protocol.version=2" "--no-optional-locks" "--no-pager" "fetch" "--quiet" "--prune" "origin" "+refs/heads/*:refs/remotes/origin/*"
`

However, if I copy and paste that into a flatpak shell (`flatpak run --command=sh --devel com.gitbutler.app`), the command does run successfully :thinking: 

Aslo, oddly if I execute the gitbutler binary fromxthe flatpak sh environment manually, the app launches and does not run into this error. What might be the difference there? Between launching the flatpak via flatpak run and exec-ing into the flatpak and launching the app via `./gitbutler`? 

Also nornally this auth process triggers a gnome portal password prompt the first time I launch the app. This wasn't happening from the flatpak, not sure if this could be related. As it did work when launched from shell-ed in the flatpak (`./gitbutler`) without the pw prompt 🤔 

### Additional Information

I have a feeling I'm just missing some sort of permission.

<details>
<summary>Current manifest</summary>

```yml
id: com.gitbutler.app

runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk

command: gitbutler-tauri
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  - --share=network
  - --filesystem=/tmp
  - --filesystem=/sys
  - --filesystem=/var
  - --filesystem=host
  # - --talk-name=com.gitbutler.app
  # - --filesystem=xdg-run/gvfs
  # - --filesystem=xdg-run/gvfs
  # - --filesystem=xdg-run/gvfsd
  - --allow=devel
  - --socket=ssh-auth
  - --socket=gpg-agent
  - --socket=system-bus
  - --socket=session-bus
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
  - --filesystem=xdg-run/gnupg:ro
  # - --filesystem=xdg-config/kdeglobals:ro
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.freedesktop.Flatpak
  - --talk-name=org.kde.kwalletd6
  - --talk-name=org.kde.kwalletd5
  - --talk-name=org.gnome.keyring.SystemPrompter
  # - --system-talk-name=org.freedesktop.login1
  # - --talk-name=org.freedesktop.Notifications
  # - --talk-name=org.freedesktop.secrets

separate-locales: false
modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        path: com.gitbutler.app.metainfo.xml
      - type: file
        dest-filename: gitbutler.deb
        url: file:///opt/gitbutler/gitbutler/target/debug/bundle/deb/GitButler Nightly_0.0.0_amd64.deb
        sha256: 7a6da73698bb4f88a7487291ee7b727ef4ef6bce2adaa74acea8fdbc9220c7b8
      # - type: file
      #   dest-filename: gitbutler.deb
      #   url: https://releases.gitbutler.com/releases/release/0.13.11-1445/linux/x86_64/GitButler_0.13.11_amd64.deb
      #   sha256: 6495589f30c0b5b7d894e268fae6bd569d4e01cbf33de22df262b07cab0507f3
      #   only-arches:
      #     - x86_64
      #   x-checker-data:
      #     type: json
      #     url: https://app.gitbutler.com/releases
      #     version-query: .version
      #     timestamp-query: .pub_date
      #     url-query: .platforms."linux-x86_64".url | sub(".AppImage.tar.gz"; ".deb")
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/gitbutler-tauri /app/bin/gitbutler-tauri
      - install -Dm755 usr/bin/gitbutler-git-askpass /app/bin/gitbutler-git-askpass
      - install -Dm755 usr/bin/gitbutler-git-setsid /app/bin/gitbutler-git-setsid
      # - install -Dm644 usr/share/applications/GitButler.desktop /app/share/applications/com.gitbutler.app.desktop
      - install -Dm644 usr/share/applications/GitButler\ Nightly.desktop /app/share/applications/com.gitbutler.app.desktop
      - desktop-file-edit --set-icon=com.gitbutler.app /app/share/applications/com.gitbutler.app.desktop
      - |
        for size in 32x32 128x128 256x256@2; do
          install -Dm644 usr/share/icons/hicolor/${size}/apps/gitbutler-tauri.png /app/share/icons/hicolor/${size}/apps/com.gitbutler.app.png
        done
      - install -Dm644 com.gitbutler.app.metainfo.xml /app/share/metainfo/com.gitbutler.app.metainfo.xml
      # - rm -r *.deb control.tar.* data.tar.gz debian-binary usr
```

</details>

<details>
<summary>Current metainfo.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>com.gitbutler.app</id>
  <name>GitButler</name>

  <developer id="com.gitbutler">
    <name>GitButler Team</name>
  </developer>

  <metadata_license>CC0-1.0</metadata_license>
  <project_license>LicenseRef-FSL-1.1-MIT=https://github.com/gitbutlerapp/gitbutler/blob/master/LICENSE.md</project_license>

  <url type="homepage">https://gitbutler.com/</url>
  <url type="bugtracker">https://github.com/gitbutlerapp/gitbutler/issues</url>
  <url type="help">https://docs.gitbutler.com/</url>

  <summary>Git branch management tool</summary>

  <icon type="stock">com.gitbutler.app</icon>
  <description>
    <p>VSCodium combines the simplicity of a code editor with what developers need for the core
      edit-build-debug cycle.</p>
  </description>
  <categories>
    <category>Development</category>
  </categories>
  <branding>
    <color type="primary" scheme_preference="light">#3cb4ae</color>
    <color type="primary" scheme_preference="dark">#3cb4ae</color>
  </branding>
  <launchable type="desktop-id">com.gitbutler.app.desktop</launchable>
  <releases>
    <release version="0.13.11" date="2024-11-05">
      <description></description>
    </release>
  </releases>

  <provides>
    <binary>git-butler</binary>
  </provides>
</component>
```

</details>

Sidenote: there is a `com.gitbutler.gitbutler` on Flathub, however, that was a community created package which exhibits the same issue as above. We're now trying to create a first party flatpak.
